project:
  type: website
  render:
    - "**/*.qmd"

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "<img src='/images/hands-on.png' class='nav-icon'> Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
    - text: "<img src='/images/take-home.png' class='nav-icon'> Take-Home Exercise"
      menu:
        - text: "Take-Home Exercise 1"
          href: "TH_Ex/TH_Ex01/TH_Ex01.html"
        - text: "Take-Home Exercise 2"
          href: "TH_Ex/TH_Ex02/TH_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - sketchy
      - custom.scss
    css: styles.css
    toc: true
    include-in-header: header-for-photo-gallery-feature.html
    
      

editor: visual


  