{
  "hash": "1a99d8ee46485c18a73ab44472ae37d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 1\"\nauthor: \"Huang Kuan Yu\"\ndate: \"2026-05-05\"\ndate-modified: \"last-modified\" \n  \nformat: \n  html: \n    toc: true \n    toc-expand: 4 \n    fig-width: 12\n    fig-height: 8\n    \nexecute:\n  echo: true \n  eval: true \n  warning: false \n  freeze: true\n---\n\n## 1 Overview\n\n### 1.1 Background\n\nMotor insurance portfolios contain heterogeneous variables including policyholder demographics, vehicle characteristics, premium amounts, exposure periods, and claims outcomes. Understanding how these variables interact is essential for insurers to evaluate underwriting risk, portfolio profitability, and customer retention. Visual analytics provides an effective approach for identifying distributional patterns, claim concentration, and potential risk segments that may not be observable through summary statistics alone.\n\n### 1.2 Objectives\n\nThe objectives of this assignment are:\n\n1.  Assess data quality through evaluation of missing values, zero inflation, and variable consistency.\n\n2.  Transform raw insurance records into analysis-ready features through cleaning and feature engineering.\n\n3.  Examine distributions of portfolio characteristics including demographics, policy types, premiums, and claims behaviour.\n\n4.  Investigate relationships between customer characteristics, policy attributes, and portfolio performance metrics.\n\n5.  Derive business insights related to claim frequency, retention behaviour, underwriting risk, and insurance profitability.\n\n### 1.3 Analytical Questions\n\nThis analysis seeks to address the following questions:\n\n1.  What are the characteristics and distributions of key variables within the motor insurance portfolio?\n\n2.  Which variables contain substantial missing values or zero values, and how might these affect analysis?\n\n3.  How are premiums, exposures, and claim outcomes distributed across policyholders, and do these distributions suggest concentration of risk?\n\n4.  What relationships exist between customer characteristics, vehicle attributes, premiums, and claims?\n\n5.  Which customer, vehicle, or policy characteristics appear associated with elevated claim frequency or underwriting risk?\n\n## 2 Packages & Data Sources\n\n### 2.1 Packages\n\nThe analysis utilises several packages to support data wrangling, visualisation, and presentation consistency:\n\n- `tidyverse`: data transformation and visualisation workflows\n- `readxl`: importing metadata from the variable description workbook\n- `scales`: formatting numerical labels and percentages\n- `gganimate`: creating animated visualisations where temporal changes are explored\n- `showtext`: custom font rendering to improve readability and maintain consistent aesthetics\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse,\n  readxl,\n  scales,\n  gganimate,\n  showtext\n)\nlibrary(showtext)\n\nfont_add_google(\"Cabin Sketch\", \"Cabin Sketch\")\nfont_add_google(\"DM Sans\", \"DM Sans\")\n\nshowtext_auto()\n```\n:::\n\n\nA customised plotting theme was applied across all visualisations to maintain consistency in style and improve readability. The theme uses a clean white background, subtle gridlines, and a pastel colour palette aligned with the website design.\n\nClick **Show code** below to view the plotting theme and colour palette configuration used across all visualisations.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nprimary_color <- \"#A8D8EA\"\nsecondary_color <- \"#FFF2A8\"\nthird_color <- \"#B8E0D2\"\nfourth_color <- \"#D7C6FF\"\nfifth_color <- \"#FFD1DC\"\n\ntext_dark <- \"#4a4a4a\"\ngrid_light <- \"#f0f0f0\"\n\ntheme_va <- function() {\n\ntheme_minimal() +\n\ntheme(\n\ntext = element_text(family = \"DM Sans\", color = text_dark),\n\nplot.title = element_text(\nfamily = \"Cabin Sketch\",\nsize = 48,\nface = \"bold\",\ncolor = text_dark,\nhjust = 0.5,\nmargin = margin(b = 20)\n),\n\naxis.title = element_text(\nfamily = \"DM Sans\",\nsize = 24,\ncolor = text_dark\n),\n\naxis.text = element_text(\nfamily = \"DM Sans\",\nsize = 20,\ncolor = text_dark\n),\n\nlegend.title = element_text(\nfamily = \"DM Sans\",\nsize = 22,\ncolor = text_dark\n),\n\nlegend.text = element_text(\nfamily = \"DM Sans\",\nsize = 20,\ncolor = text_dark\n),\n\nplot.caption = element_text(\nfamily = \"DM Sans\",\nsize = 18,\ncolor = text_dark\n),\n\nstrip.text = element_text(\nfamily = \"DM Sans\",\nsize = 22,\ncolor = text_dark\n),\n\npanel.grid.major = element_line(\ncolor = \"#eeeeee\",\nlinewidth = .4\n),\n\npanel.grid.minor = element_blank(),\n\nplot.background = element_rect(\nfill = \"white\",\ncolor = NA\n),\n\npanel.background = element_rect(\nfill = \"white\",\ncolor = NA\n),\n\nlegend.position = \"bottom\")}\nshowtext_auto()\n```\n:::\n\n\n### 2.2 Dataset Description\n\nThe analysis uses two datasets provided as supporting materials for this assignment. The first dataset contains the raw motor insurance portfolio records, while the second dataset provides descriptions of the variables included in the portfolio. The dataset spans policy observations between 2022 and 2024, enabling limited longitudinal analysis of policy retention, premium evolution, and claim behaviour over time.\n\n### Dataset 1: Motor Insurance Portfolio Dataset\n\nThe primary dataset contains observations related to motor insurance policies and includes information associated with policyholders, insured vehicles, premiums, exposure periods, and insurance claims. The variables may generally be categorised into several groups:\n\n- **Policyholder characteristics:** demographic or customer-related information.\n\n- **Vehicle characteristics:** information describing insured vehicles such as fuel type, vehicle category, or circulation area.\n\n- **Insurance policy information:** variables describing policy coverage and portfolio details.\n\n- **Premium variables:** monetary values associated with insurance premiums.\n\n- **Claims variables:** counts of claims and incurred claim amounts across different claim categories.\n\n- **Exposure variables:** measures representing insurance exposure duration or risk exposure.\n\nThe dataset contains both **categorical** and **continuous numerical variables**, requiring preprocessing before visual analysis.\n\nPreliminary inspection indicates that some claim-related variables contain a high proportion of zero values. This is expected in insurance datasets because many policyholders do not submit claims during the observation period. Such zero inflation may influence the interpretation of distributions and subsequent analysis.\n\n### Dataset 2: Variable Description Workbook\n\nThe second dataset provides metadata describing variables contained within the motor insurance portfolio. This supplementary document is used to:\n\n- Interpret variable meanings accurately.\n\n- Identify appropriate data types.\n\n- Support variable selection decisions during preprocessing.\n\n- Facilitate understanding of claim-related and premium-related measures.\n\nThe variable description file serves as a reference throughout data wrangling to ensure variables are correctly transformed and interpreted before analysis.\n\n## 3 Data Wrangling\n\nBefore performing visual analytics, the raw insurance datasets underwent preprocessing to improve consistency, interpretability, and analytical reliability. Insurance datasets often contain missing values, mixed variable types, repeated policy records across years, and variables with highly skewed or zero-dominated distributions. Therefore, several preprocessing steps were conducted, including data inspection, missing value assessment, zero value evaluation, variable transformation, feature engineering, and metric aggregation.\n\nThese preprocessing procedures help ensure that subsequent portfolio analysis and exploratory visualisation reflect meaningful business patterns rather than artefacts introduced by inconsistent data formatting or incomplete records.\n\n### 3.1 Import Raw Data\n\nIn this section, the first thing to do is import both the motor insurance dataset and variable description file.\n\n::: code-tip\n**Coding Details** - `read_delim()` imports the motor insurance portfolio dataset from a CSV file where values are separated by semicolons (`;`). `show_col_types = FALSE` suppresses the message displaying detected column data types during import.\n\n- `read_excel()` loads the Excel file containing descriptions of variables into R. This file serves as a data dictionary to provide definitions and meanings for variables in the main dataset.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_raw <- read_delim(\n  \"data/Dataset of motor insurance portfolio.csv\",\n  delim = \";\",\n  show_col_types = FALSE\n)\n\nvariable_desc <- read_excel(\n  \"data/Descriptive of variables.xlsx\"\n)\n```\n:::\n\n\n### 3.2 Initial Data Inspection\n\nInitial inspection was conducted using `glimpse()`, `summary()`, and `names()` to examine dataset structure, variable types, distributions, and potential anomalies.\n\nThis revealed a mixture of categorical and continuous variables representing:\n\n- Policy information\n\n- Driver characteristics\n\n- Vehicle attributes\n\n- Premium components\n\n- Claims records\n\n- Exposure measures\n\nThese variables span multiple years (2022–2024), enabling longitudinal portfolio analysis.\n\n::: code-tip\n**Coding Details**\n\n- `glimpse()` provides a compact overview of the dataset structure, displaying variable names, data types, and sample values for quick inspection. This helps identify whether variables are stored in appropriate formats.\n\n- `summary()` generates descriptive statistics for each variable, such as minimum, maximum, median, mean, and frequency counts. This is useful for detecting unusual values or understanding data distributions.\n\n- `names()` returns the column names of the dataset. This allows you to review available variables and reference them accurately in later analysis.\n:::\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(motor_raw)\nsummary(motor_raw)\nnames(motor_raw)\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   insured_id          year         policy_type       policy_status   \n Min.   :     1   Min.   :2022   Length   :354140   Length   :354140  \n 1st Qu.: 33342   1st Qu.:2023   N.unique :     5   N.unique :     2  \n Median : 66840   Median :2023   N.blank  :     0   N.blank  :     0  \n Mean   : 76045   Mean   :2023   Min.nchar:     2   Min.nchar:     1  \n 3rd Qu.:112949   3rd Qu.:2024   Max.nchar:     6   Max.nchar:     1  \n Max.   :185678   Max.   :2024                                        \n                                                                      \n   business_type    payment_frequency     bonus_score       driver_age   \n Length   :354140   Length   :354140   Length   :354140   Min.   :18.00  \n N.unique :     2   N.unique :     3   N.unique :     3   1st Qu.:39.00  \n N.blank  :     0   N.blank  :     0   N.blank  :     0   Median :48.00  \n Min.nchar:     1   Min.nchar:     1   Min.nchar:     1   Mean   :49.01  \n Max.nchar:     2   Max.nchar:     1   Max.nchar:     1   3rd Qu.:58.00  \n                                                          Max.   :90.00  \n                                                                         \n  vehicle_age    age_driving_licence     fuel_type      vehicle_value   \n Min.   : 0.00   Min.   : 0.00       Length   :354140   Min.   :  1630  \n 1st Qu.:17.00   1st Qu.:19.00       N.unique :     2   1st Qu.: 18608  \n Median :25.00   Median :20.00       N.blank  :     0   Median : 24730  \n Mean   :25.92   Mean   :22.99       Min.nchar:     1   Mean   : 26977  \n 3rd Qu.:35.00   3rd Qu.:25.00       Max.nchar:     1   3rd Qu.: 32252  \n Max.   :68.00   Max.   :80.00       NAs      :  1287   Max.   :374034  \n NAs    :2       NAs    :2                              NAs    :513     \n     seats       power_to_weight_ratio   vehicle_brand    municipality_type \n Min.   :2.000   Min.   : 0.00         Length   :354140   Length   :354140  \n 1st Qu.:5.000   1st Qu.:10.74         N.unique :    68   N.unique :     3  \n Median :5.000   Median :12.05         N.blank  :     0   N.blank  :     0  \n Mean   :5.084   Mean   :12.33         Min.nchar:     2   Min.nchar:     1  \n 3rd Qu.:5.000   3rd Qu.:13.73         Max.nchar:    12   Max.nchar:     2  \n Max.   :9.000   Max.   :64.81                                              \n                                                                            \n  circulation_area  total_premium    liability_premium property_damage_premium\n Length   :354140   Min.   :   0.0   Min.   :   0.00   Min.   :   0.00        \n N.unique :     2   1st Qu.: 146.1   1st Qu.:  92.52   1st Qu.:   0.00        \n N.blank  :     0   Median : 257.9   Median : 165.78   Median :   0.00        \n Min.nchar:     1   Mean   : 296.7   Mean   : 180.71   Mean   :  73.52        \n Max.nchar:     1   3rd Qu.: 385.0   3rd Qu.: 237.83   3rd Qu.:  83.62        \n                    Max.   :5107.6   Max.   :2320.77   Max.   :3736.73        \n                                                                              \n theft_premium       fire_premium     glass_premium    \n Min.   :   0.000   Min.   : 0.0000   Min.   :  0.000  \n 1st Qu.:   1.808   1st Qu.: 0.2889   1st Qu.:  7.417  \n Median :   5.902   Median : 0.8644   Median : 15.387  \n Mean   :  11.249   Mean   : 1.5105   Mean   : 19.497  \n 3rd Qu.:  13.519   3rd Qu.: 1.8182   3rd Qu.: 26.912  \n Max.   :1047.036   Max.   :72.0891   Max.   :387.608  \n                                                       \n legal_protection_premium occupants_premium  total_claims     liability_claims\n Min.   :  0.000          Min.   : 0.0000   Min.   : 0.0000   Min.   :0.0000  \n 1st Qu.:  3.820          1st Qu.: 0.9441   1st Qu.: 0.0000   1st Qu.:0.0000  \n Median :  7.262          Median : 1.8261   Median : 0.0000   Median :0.0000  \n Mean   :  8.268          Mean   : 1.9651   Mean   : 0.2177   Mean   :0.1066  \n 3rd Qu.: 10.966          3rd Qu.: 2.6200   3rd Qu.: 0.0000   3rd Qu.:0.0000  \n Max.   :175.056          Max.   :68.6461   Max.   :18.0000   Max.   :8.0000  \n                                                                              \n liability_property_claims liability_injury_claims property_claims   \n Min.   :0.00000           Min.   :0.00000         Min.   : 0.00000  \n 1st Qu.:0.00000           1st Qu.:0.00000         1st Qu.: 0.00000  \n Median :0.00000           Median :0.00000         Median : 0.00000  \n Mean   :0.09281           Mean   :0.01376         Mean   : 0.06295  \n 3rd Qu.:0.00000           3rd Qu.:0.00000         3rd Qu.: 0.00000  \n Max.   :8.00000           Max.   :3.00000         Max.   :15.00000  \n                                                                     \n  theft_claims       fire_claims         glass_claims    \n Min.   :0.000000   Min.   :0.0000000   Min.   :0.00000  \n 1st Qu.:0.000000   1st Qu.:0.0000000   1st Qu.:0.00000  \n Median :0.000000   Median :0.0000000   Median :0.00000  \n Mean   :0.005326   Mean   :0.0002824   Mean   :0.03271  \n 3rd Qu.:0.000000   3rd Qu.:0.0000000   3rd Qu.:0.00000  \n Max.   :2.000000   Max.   :1.0000000   Max.   :3.00000  \n                                                         \n legal_protection_claims occupants_claims    total_incurred    \n Min.   :0.000000        Min.   :0.0000000   Min.   :     0.0  \n 1st Qu.:0.000000        1st Qu.:0.0000000   1st Qu.:     0.0  \n Median :0.000000        Median :0.0000000   Median :     0.0  \n Mean   :0.009753        Mean   :0.0001214   Mean   :   208.6  \n 3rd Qu.:0.000000        3rd Qu.:0.0000000   3rd Qu.:     0.0  \n Max.   :2.000000        Max.   :1.0000000   Max.   :571128.3  \n                                                               \n liability_incurred liability_property_incurred liability_injury_incurred\n Min.   :     0.0   Min.   :    0.00            Min.   :     0.00        \n 1st Qu.:     0.0   1st Qu.:    0.00            1st Qu.:     0.00        \n Median :     0.0   Median :    0.00            Median :     0.00        \n Mean   :   133.7   Mean   :   65.75            Mean   :    67.96        \n 3rd Qu.:     0.0   3rd Qu.:    0.00            3rd Qu.:     0.00        \n Max.   :561759.8   Max.   :34553.88            Max.   :560025.59        \n                                                                         \n property_incurred  theft_incurred      fire_incurred       glass_incurred   \n Min.   :    0.00   Min.   :    0.000   Min.   :0.000e+00   Min.   :   0.00  \n 1st Qu.:    0.00   1st Qu.:    0.000   1st Qu.:0.000e+00   1st Qu.:   0.00  \n Median :    0.00   Median :    0.000   Median :0.000e+00   Median :   0.00  \n Mean   :   52.66   Mean   :    4.511   Mean   :7.629e-01   Mean   :  12.59  \n 3rd Qu.:    0.00   3rd Qu.:    0.000   3rd Qu.:0.000e+00   3rd Qu.:   0.00  \n Max.   :27542.43   Max.   :40324.888   Max.   :2.827e+04   Max.   :4533.40  \n                                                                             \n legal_protection_incurred occupants_incurred  total_exposure  \n Min.   :   0.000          Min.   :    0.000   Min.   :0.0000  \n 1st Qu.:   0.000          1st Qu.:    0.000   1st Qu.:0.4438  \n Median :   0.000          Median :    0.000   Median :0.8384  \n Mean   :   3.323          Mean   :    1.013   Mean   :0.7069  \n 3rd Qu.:   0.000          3rd Qu.:    0.000   3rd Qu.:1.0000  \n Max.   :9889.851          Max.   :69000.000   Max.   :1.0000  \n                                                               \n liability_exposure\n Min.   :0.0000    \n 1st Qu.:0.4438    \n Median :0.8384    \n Mean   :0.7069    \n 3rd Qu.:1.0000    \n Max.   :1.0000    \n                   \n```\n\n\n:::\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\nSeveral variables were stored in unsuitable formats for aggregation and visualisation. Converting these variables ensures subsequent calculations such as claim frequency and loss ratios are computed correctly and reduces risks of misleading analytical outputs.\n:::\n\n### 3.3 Missing Value Analysis\n\nMissing values should be examined because they can reduce data quality and affect the accuracy of analysis results. Large amounts of missing data may introduce bias or distort patterns and relationships within the dataset. Identifying missing values helps determine appropriate cleaning methods, such as removal or imputation, before further analysis.\n\n::: code-tip\n**Coding Details**\n\n- `summarise(across(everything(), ~ mean(is.na(.))))` calculates the proportion of missing values for every variable by taking the mean of `TRUE/FALSE` outputs from `is.na()`.\n\n- `pivot_longer()` reshapes the summary into a long format with variable names and corresponding missing ratios, while `mutate()` converts missing ratios into percentages for easier interpretation. `arrange(desc(missing_ratio))` then sorts variables from highest to lowest missingness.\n\n- `na_summary` displays the final table summarising missing value percentages across all variables, helping identify columns that may require cleaning or imputation.\n:::\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nna_summary <- motor_raw %>%\n  summarise(across(everything(), ~ mean(is.na(.)))) %>%\n  pivot_longer(\n    everything(),\n    names_to = \"variable\",\n    values_to = \"missing_ratio\"\n  ) %>%\n  mutate(\n    missing_percent = missing_ratio * 100\n  ) %>%\n  arrange(desc(missing_ratio))\n\nna_summary\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 47 × 3\n   variable            missing_ratio missing_percent\n   <chr>                       <dbl>           <dbl>\n 1 fuel_type              0.00363           0.363   \n 2 vehicle_value          0.00145           0.145   \n 3 vehicle_age            0.00000565        0.000565\n 4 age_driving_licence    0.00000565        0.000565\n 5 insured_id             0                 0       \n 6 year                   0                 0       \n 7 policy_type            0                 0       \n 8 policy_status          0                 0       \n 9 business_type          0                 0       \n10 payment_frequency      0                 0       \n# ℹ 37 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\nMissing value analysis showed relatively low levels of incompleteness across variables, suggesting overall good data quality. Since no variables exceeded the 30% missingness threshold, variable removal was unnecessary. Retaining these variables preserves potentially important predictors associated with underwriting risk while minimising information loss.\n:::\n\n### 3.4 Zero Value Analysis\n\nUnlike missing values, zero values frequently represent meaningful business outcomes in insurance datasets rather than data quality problems. For example:\n\n- Zero claims → no claims submitted\n\n- Zero incurred cost → no claim payout\n\n- Zero premium component → coverage not purchased\n\nTherefore, zero value analysis was performed to distinguish between expected insurance behaviour and potentially problematic variables.\n\n::: code-tip\n**Coding Details**\\\n- `where(is.numeric)` restricts the calculation to numeric variables only. `mean(. == 0, na.rm = TRUE)` computes the proportion of zero values by treating zeros as `TRUE` and non-zero values as `FALSE`, while excluding missing values (`NA`).\n:::\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nzero_summary <- motor_raw %>%\n  summarise(\n    across(\n      where(is.numeric),\n      ~ mean(. == 0, na.rm = TRUE)\n    )\n  ) %>%\n  pivot_longer(\n    everything(),\n    names_to = \"variable\",\n    values_to = \"zero_ratio\"\n  ) %>%\n  mutate(\n    zero_percent = zero_ratio * 100\n  ) %>%\n  arrange(desc(zero_ratio))\n\nzero_summary\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 38 × 3\n   variable                  zero_ratio zero_percent\n   <chr>                          <dbl>        <dbl>\n 1 occupants_claims               1.000        100.0\n 2 occupants_incurred             1.000        100.0\n 3 fire_incurred                  1.000        100.0\n 4 fire_claims                    1.000        100.0\n 5 theft_claims                   0.995         99.5\n 6 theft_incurred                 0.995         99.5\n 7 legal_protection_incurred      0.991         99.1\n 8 legal_protection_claims        0.990         99.0\n 9 liability_injury_incurred      0.987         98.7\n10 liability_injury_claims        0.987         98.7\n# ℹ 28 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\nZero values were observed across multiple variables, particularly in claim-related measures, reflecting that many policyholders do not submit claims during a coverage period. In some cases, zero values may also occur because policyholders purchase specialised insurance products where certain claim categories or coverages are not applicable.\n\nAs these zero-heavy distributions can skew visualisations and mask underlying patterns, subsequent analyses focus on `total_claims`, `total_incurred`, `total_exposure`, and `total_premium`. These variables provide more meaningful insights into portfolio profitability, claim behaviour, and overall risk performance.\n:::\n\n### 3.5 Data Cleaning and Type Conversion\n\nThe `mutate()` function was used to convert variables into appropriate numerical or categorical formats according to their analytical purpose.\n\nVariables were transformed into appropriate data types to support statistical aggregation and visualisation.\n\nSpecifically:\n\n- `factor()` was applied to categorical variables such as:\n\n- year\n\n- policy type\n\n- policy status\n\n- fuel type\n\n- vehicle brand\n\n- `numeric()` conversion was applied to continuous measures including:\n\n- driver age\n\n- claims\n\n- incurred amount\n\n- exposure\n\n- premium\n\nProper variable typing prevents analytical errors and ensures accurate grouping, summarisation, and visual encoding.\n\nFor example, treating policy type as numeric would incorrectly imply ordering relationships between insurance products.\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_clean <- motor_raw %>%\n  mutate(\n    year = factor(year),\n    policy_type = factor(policy_type),\n    policy_status = factor(policy_status),\n    fuel_type = factor(fuel_type),\n    vehicle_brand = factor(vehicle_brand),\n    driver_age = as.numeric(driver_age),\n    total_claims = as.numeric(total_claims),\n    total_incurred = as.numeric(total_incurred),\n    total_exposure = as.numeric(total_exposure),\n    total_premium = as.numeric(total_premium)\n  )\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <fct> COMP_E, COMP_E, COMP_E, COMP_E, COMP_E, CO…\n$ policy_status               <fct> C, A, A, A, A, A, A, A, A, A, A, A, A, A, …\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <fct> G, D, D, D, D, D, D, D, D, D, D, D, D, D, …\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <fct> PORSCHE, MERCEDES, MERCEDES, MERCEDES, KIA…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n:::\n\nAfter conversion, the dataset was standardised into a cleaner structure suitable for aggregation and exploratory analysis.\n\n### 3.6 Driver Retention Classification\n\nInsurance retention reflects customer persistence and portfolio stability. To evaluate retention behaviour, policyholders were grouped according to the number of active years observed within the dataset.\n\nRetention groups were defined as:\n\n- 1-year group → retained for one active year\n\n- 2-year group → retained for two active years\n\n- 3-year group → retained throughout all observed years\n\nRetention classification enables later comparison between long-term and short-term policyholders.\n\n::: code-tip\n**Coding Details**\n\n- `group_by(insured_id)` groups records by individual policyholders, while `sum(policy_status == \"A\")` counts the number of years each policyholder remained active.\n\n- `case_when()` categorises policyholders into retention groups based on their active years, allowing retention behaviour to be segmented.\n\n- `count()` then summarises the number of policyholders within each retention group.\n:::\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndriver_survival <- motor_clean %>%\n  group_by(insured_id) %>%\n  summarise(\n    active_years = sum(policy_status == \"A\", na.rm = TRUE),\n    retention_group = case_when(\n      active_years >= 3 ~ \"3-year group\",\n      active_years == 2 ~ \"2-year group\",\n      active_years == 1 ~ \"1-year group\",\n      TRUE ~ \"0-year group\"\n    ),\n    .groups = \"drop\"\n  )\n\nsurvival_summary <- driver_survival %>%\n  count(retention_group)\n\nsurvival_summary\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  retention_group     n\n  <chr>           <int>\n1 0-year group     5893\n2 1-year group    85522\n3 2-year group    52499\n4 3-year group    41764\n```\n\n\n:::\n:::\n\n:::\n\nRetention classification enables comparison between policyholders with different persistence durations and supports later analysis of whether retention patterns are associated with premiums, claims behaviour, or policy characteristics.\n\n### 3.7 Policy Type Distribution\n\nThe frequency distribution of policy types was calculated to understand portfolio composition.\n\nInsurance portfolios concentrated within a small number of products may experience elevated exposure to adverse claim behaviour in those segments.\n\nTherefore, identifying dominant policy categories provides context for later profitability comparisons.\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_distribution <- motor_clean %>%\n  count(policy_type, sort = TRUE)\n\npolicy_distribution\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  policy_type      n\n  <fct>        <int>\n1 CC          204636\n2 COMP_E       91199\n3 TPG          36367\n4 COMP_N       16181\n5 TP            5757\n```\n\n\n:::\n:::\n\n:::\n\nThe portfolio appears concentrated within selected policy categories, suggesting underwriting exposure may not be evenly distributed across insurance products.\n\n### 3.8 Aggregated Insurance Metrics\n\nPortfolio metrics were aggregated across years, policy types, and policy activity status to support comparative analysis of claims behaviour and underwriting performance.\n\nAggregation reduces variability at the individual policy level and facilitates identification of broader temporal and segment-level patterns within the portfolio.\n\nThe following insurance metrics were computed:\n\nClaim Frequency= Total Claims/Total Exposure\n\nLoss Ratio= Total Incurred/Total Premium\n\nClaim frequency measures the average occurrence of claims relative to exposure, while loss ratio evaluates underwriting performance by comparing incurred losses against collected premiums.\n\nThe `group_by()` and `summarise()` functions from dplyr were used to aggregate portfolio metrics across different dimensions:\n\n- `group_by(year)` → summarises portfolio performance annually\n\n- `group_by(year, policy_type)` → compares performance across insurance products over time\n\n- `group_by(year, status_group)` → compares metrics between active and inactive policies\n\nThe `summarise()` function computes aggregated totals for:\n\n- `total_claims`\n\n- `total_incurred`\n\n- `total_exposure`\n\n- `total_premium`\n\nwhile `n()` calculates the number of policies within each group.\n\nThese aggregated datasets serve as the basis for subsequent analyses involving claim frequency, loss ratio, retention behaviour, and underwriting profitability trends.\n\n::: panel-tabset\n#### Metrics by Year\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nyear_metrics <- motor_clean %>%\n  group_by(year) %>%\n  summarise(\n    total_claims = sum(total_claims, na.rm = TRUE),\n    total_incurred = sum(total_incurred, na.rm = TRUE),\n    total_exposure = sum(total_exposure, na.rm = TRUE),\n    total_premium = sum(total_premium, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nyear_metrics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  year  total_claims total_incurred total_exposure total_premium\n  <fct>        <dbl>          <dbl>          <dbl>         <dbl>\n1 2022         12665      12270105.         41912.     18697928.\n2 2023         25158      23488354.         82399.     35344308.\n3 2024         39276      38106351.        126014.     51037433.\n```\n\n\n:::\n:::\n\n\n#### Metrics by Policy Type and Year\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\npolicy_year_metrics <- motor_clean %>%\n  group_by(year, policy_type) %>%\n  summarise(\n    total_claims = sum(total_claims, na.rm = TRUE),\n    total_incurred = sum(total_incurred, na.rm = TRUE),\n    total_exposure = sum(total_exposure, na.rm = TRUE),\n    total_premium = sum(total_premium, na.rm = TRUE),\n    policy_count = n(),\n    .groups = \"drop\"\n  )\n\npolicy_year_metrics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 7\n   year  policy_type total_claims total_incurred total_exposure total_premium\n   <fct> <fct>              <dbl>          <dbl>          <dbl>         <dbl>\n 1 2022  CC                  5936       6055316.         24750.      9202621.\n 2 2022  COMP_E              3906       3861809.          9955.      5852301.\n 3 2022  COMP_N              1704       1282022.          2058.      1761175.\n 4 2022  TP                    56         48618.           512.       160840.\n 5 2022  TPG                 1063       1022341.          4638.      1720991.\n 6 2023  CC                 10592       9926718.         47747.     16906919.\n 7 2023  COMP_E              8561       8195734.         20862.     11696980.\n 8 2023  COMP_N              4163       3295098.          4252.      3570041.\n 9 2023  TP                   138        154697.          1157.       315634.\n10 2023  TPG                 1704       1916107.          8380.      2854733.\n11 2024  CC                 15314      15581525.         71738.     23692229.\n12 2024  COMP_E             14220      14309533.         34223.     18163110.\n13 2024  COMP_N              7040       5132162.          6033.      5013335.\n14 2024  TP                   313        350119.          2134.       543074.\n15 2024  TPG                 2389       2733014.         11887.      3625685.\n# ℹ 1 more variable: policy_count <int>\n```\n\n\n:::\n:::\n\n\n#### Metrics by Policy Activity Status and Year\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nstatus_year_metrics <- motor_clean %>%\n  mutate(\n    status_group = if_else(\n      policy_status == \"A\",\n      \"Active\",\n      \"Not Active\"\n    )\n  ) %>%\n  group_by(year, status_group) %>%\n  summarise(\n    total_claims = sum(total_claims, na.rm = TRUE),\n    total_incurred = sum(total_incurred, na.rm = TRUE),\n    total_exposure = sum(total_exposure, na.rm = TRUE),\n    total_premium = sum(total_premium, na.rm = TRUE),\n    policy_count = n(),\n    .groups = \"drop\"\n  )\n\nstatus_year_metrics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  year  status_group total_claims total_incurred total_exposure total_premium\n  <fct> <chr>               <dbl>          <dbl>          <dbl>         <dbl>\n1 2022  Active              11316      10302863.         39262.     17257013.\n2 2022  Not Active           1349       1967242.          2650.      1440915.\n3 2023  Active              21802      19276099.         75560.     31920779.\n4 2023  Not Active           3356       4212255.          6839.      3423529.\n5 2024  Active              33770      31899227.        115321.     46222021.\n6 2024  Not Active           5506       6207124.         10694.      4815412.\n# ℹ 1 more variable: policy_count <int>\n```\n\n\n:::\n:::\n\n:::\n\n### 3.9 Age Group Creation\n\nDriver age was transformed into categorical age groups to simplify risk segmentation.\n\nGrouping continuous age values facilitates comparison across demographic categories and improves interpretability in visualisations.\n\nThe selected age bands approximately represent different driving experience stages, from younger drivers with potentially higher risk exposure to older drivers with more driving experience.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_clean <- motor_clean %>%\n  mutate(\n    age_group = cut(\n      driver_age,\n      breaks = c(18,25,35,45,55,65,100)\n    )\n  )\n```\n:::\n\n\nAge segmentation enables examination of whether claims behaviour or premiums differ systematically across driver life stages.\n\n### 3.10 Final Dataset Summary\n\nThe final cleaned dataset integrates transformed variables, derived retention groups, aggregated metrics, and demographic segments.\n\nThis processed dataset serves as the foundation for subsequent univariate portfolio analysis and bivariate exploratory analysis.\n\n::: panel-tabset\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(motor_clean)\nglimpse(motor_clean)\n```\n:::\n\n\n#### The data\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 354140     48\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 48\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <fct> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <fct> COMP_E, COMP_E, COMP_E, COMP_E, COMP_E, CO…\n$ policy_status               <fct> C, A, A, A, A, A, A, A, A, A, A, A, A, A, …\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <fct> G, D, D, D, D, D, D, D, D, D, D, D, D, D, …\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <fct> PORSCHE, MERCEDES, MERCEDES, MERCEDES, KIA…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ age_group                   <fct> \"(45,55]\", \"(35,45]\", \"(35,45]\", \"(35,45]\"…\n```\n\n\n:::\n:::\n\n:::\n\n## 4 Portfolio Analysis\n\nThis section applies univariate visual analytics techniques to examine the distributions and characteristics of key variables within the motor insurance portfolio. Univariate analysis helps identify portfolio composition, demographic concentration, and customer retention patterns before exploring interactions between variables.\n\n### 4.1 Policy Type Composition\n\nThis section examines the distribution of policy types within the portfolio to understand product composition and identify dominant insurance segments. Portfolio composition provides important context for subsequent analyses involving claim behaviour, premiums, and profitability across products.\n\nA horizontal bar chart was selected because policy type is a categorical variable and frequency comparisons across categories are more easily interpreted when labels are lengthy. Ordering categories by count further highlights dominant and underrepresented policy segments within the portfolio.\n\n::: code-tip\n**Coding Details**\n\n- `recode()` renames abbreviated policy types into more descriptive labels, improving readability in the final visualisation. `count(sort = TRUE)` summarises the frequency of each policy type and orders them from most to least common.\n\n- `geom_col()` creates the bar chart, while `geom_text()` adds count and percentage labels to each bar. `coord_flip()` swaps the axes to produce a horizontal bar chart for easier comparison of long category labels.\n:::\n\n::: panel-tabset\n#### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-22-1.png){width=1152}\n:::\n:::\n\n\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_distribution <- motor_clean %>% mutate(policy_type = recode(policy_type, \"TP\" = \"Basic Third-Party Liability\", \"TPG\" = \"Third-Party Liability + Glass\", \"CC\" = \"Third-Party + Additional Coverages\", \"COMP_E\" = \"Comprehensive with Excess\", \"COMP_N\" = \"Comprehensive without Excess\")) %>% count(policy_type, sort = TRUE) %>%\n  mutate(pct = n / sum(n))\n\nggplot(policy_distribution, aes(x = reorder(policy_type, n), y = n)) +\n  geom_col(fill = primary_color, color = \"white\", alpha = .9) +\n  geom_text(aes(label = paste0(comma(n),\" (\", percent(pct, accuracy = 0.1),\")\")), hjust = -0.1, size = 10, color = text_dark, family = \"DM Sans\") +\n  coord_flip() +\n  labs(title = \"Composition of Policies by Policy Type\", x = \"Policy Type\", y = \"Number of Policies\") +\n  expand_limits(y = max(policy_distribution$n) * 1.1) +\n  theme_va()\n```\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- Third-Party + Additional Coverages (CC) dominates the portfolio, accounting for approximately 57.9% (204,636 policies) of all policies. This indicates that the portfolio is highly concentrated within a single product category.\n- Comprehensive with Excess (COMP_E) represents the second-largest segment at 25.8% (91,199 policies), while Basic Third-Party Liability (TP) contributes only 1.6% (5,757 policies), making it the least common product.\n- The strong concentration in CC and COMP_E policies suggests that policyholders generally prefer products offering broader coverage over basic liability-only protection.\n- Since dominant policy categories contribute a larger share of portfolio exposure, subsequent analyses should examine whether these products also demonstrate higher claim frequency or loss ratios, as this may disproportionately influence overall portfolio performance.\n:::\n\n::: biz-box\n**Business Implication:**\n\nA highly concentrated portfolio increases dependence on the underwriting performance of a small number of products. If dominant products experience worsening claim behaviour or adverse loss ratios, the impact on overall portfolio profitability may be substantial. Understanding concentration therefore supports risk diversification and product strategy decisions.\n:::\n\n### 4.2 Driver Age Distribution\n\nThis section examines the distribution of driver age to understand the demographic composition of policyholders within the portfolio. Age is an important characteristic because it may influence driving behaviour, risk exposure, and insurance product preferences.\n\nA histogram was selected because driver age is a continuous numerical variable. Histograms effectively reveal concentration patterns, spread, skewness, and potential outliers within continuous distributions.\n\n::: code-tip\n**Coding Details**\n\n- `geom_histogram()` groups `driver_age` into bins and displays the frequency distribution, helping identify common age ranges and overall spread of policyholders. `bins = 30` controls the number of intervals used to summarise the distribution.\n:::\n\n::: panel-tabset\n#### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-24-1.png){width=1152}\n:::\n:::\n\n\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(motor_clean, aes(x = driver_age)) +\n  geom_histogram(bins = 30, fill = primary_color, color = \"white\", alpha = .85) +\n  labs(title = \"Distribution of Driver Age\", x = \"Driver Age\", y = \"Number of Policies\") +\n  theme_va()\n```\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- Driver ages appear concentrated between approximately 35 and 60 years, indicating that the portfolio is predominantly composed of middle-aged policyholders.\n\n- Very young drivers (below 25 years) and older drivers (above 70 years) represent a relatively small proportion of the portfolio, suggesting lower participation from these demographic groups.\n\n- The distribution is slightly right-skewed, with policy counts gradually decreasing at older ages. This indicates fewer policies among senior drivers.\n\n- The concentration of middle-aged policyholders suggests the portfolio may be dominated by drivers with longer driving experience and potentially more stable insurance purchasing behaviour.\n:::\n\n::: biz-box\n**Business implication:**\n\nDriver age is frequently incorporated into insurance pricing and risk segmentation models because claim behaviour and risk exposure may differ across demographic groups. A portfolio concentrated within middle-aged drivers may imply greater dependence on the claims performance of this segment.\n:::\n\n### 4.3 Policy Status Composition Across Years\n\nThis section examines changes in policy status composition across years by comparing active and non-active policies. Analysing policy persistence provides insight into portfolio stability and potential retention patterns over time.\n\nA 100% stacked bar chart was selected because it highlights proportional changes in policy status composition across years, allowing easier comparison between active and inactive segments regardless of total portfolio size.\n\n::: code-tip\n**Coding Details**\n\n- `if_else()` groups policy statuses into simplified categories (\"Active\" and \"Not Active\") for easier comparison across years. `group_by(year)` with `mutate(pct = n / sum(n))` calculates the percentage composition of each status group within each year.\n\n- `position_stack(vjust = .5)` centres percentage labels within stacked bars, making proportions easier to interpret. `scale_fill_manual()` assigns custom colours to status groups, while `scale_y_continuous(labels = percent)` formats the y-axis as percentages.\n:::\n\n::: panel-tabset\n#### The plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-26-1.png){width=1152}\n:::\n:::\n\n\n#### The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstatus_year_summary <- motor_clean %>% mutate(status_group = if_else(policy_status == \"A\", \"Active\", \"Not Active\")) %>% count(year, status_group) %>% group_by(year) %>% mutate(pct = n / sum(n)) %>% ungroup()\n\nggplot(status_year_summary, aes(x = factor(year), y = pct, fill = status_group)) +\ngeom_col(color = \"white\", alpha = .9) +\ngeom_text(aes(label = percent(pct, accuracy = 1)), position = position_stack(vjust = .5), color = text_dark, size = 10, family = \"DM Sans\") +\nscale_fill_manual(values = c(\"Active\" = primary_color, \"Not Active\" = secondary_color)) +\nscale_y_continuous(labels = percent, limits = c(0,1)) +\nlabs(title = \"Policy Status Composition by Year\", x = \"Year\", y = \"Percentage of Policies\", fill = \"Policy Status\") +\ntheme_va()\n```\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- Active policies consistently dominate the portfolio, accounting for approximately 94% in 2022, 89% in 2023, and 88% in 2024, indicating that most policyholders maintain active coverage.\n\n- The proportion of non-active policies increases gradually from 6% (2022) to 12% (2024), suggesting a potential decline in policy retention over time.\n\n- Although active policies remain the majority, the upward trend in inactive status may indicate changing customer behaviour, increased policy cancellations, or shifts in portfolio composition.\n\n- The observed increase in inactive policies suggests that subsequent analyses should examine whether retention patterns differ across policy types, age groups, or claims behaviour.\n:::\n\n::: biz-box\n**Business Implication**\n\nCustomer retention directly influences premium stability and customer lifetime value. A rising proportion of inactive policies may indicate increasing churn risk, emphasising the importance of identifying factors associated with long-term policy retention and customer persistence.\n:::\n\n## 5 Exploratory Data Analysis\n\nThis section applies bivariate visual analytics techniques to investigate relationships between demographic characteristics, insurance products, claims behaviour, and profitability indicators. Findings support identification of factors potentially influencing portfolio profitability and volatility.\n\n### 5.1 Claim Frequency by Policy Type Over Time\n\nClaim frequency measures the average number of claims generated per unit of exposure and serves as an indicator of relative portfolio risk across policy types and years. Higher claim frequency generally suggests greater claim occurrence within a policy segment.\n\nThe metric is computed as:\n\nClaim Frequency = Total Claims / Total Exposure\n\nA line chart was selected because it effectively visualises temporal changes and enables comparison of claim frequency trends across multiple policy categories.\n\nThe analysis aggregates:\n\n- `year` → x-axis (2022–2024)\n\n- `total_claims / total_exposure` → y-axis (claim frequency)\n\n- `policy_type` → colour grouping\n\nThis facilitates comparison of how claim behaviour evolves across insurance products over time.\n\n::: code-tip\n**Coding Details**\n\n- `geom_line()` connects claim frequency values across years to highlight trends over time, while `geom_point()` emphasises individual observations for each policy type. The calculation `total_claims / total_exposure` represents claim frequency, measuring the number of claims relative to insured exposure.\n\n- `group = policy_type` ensures separate trend lines are drawn for each policy type, and `scale_color_manual()` assigns custom colours to distinguish categories.\n\n- `filter(policy_type == \"CC\")` subsets the dataset to only include policies under the \"Third-Party + Additional Coverages\" category. This allows claim frequency trends to be examined specifically for one policy type.\n\n- `geom_col()` creates bars to compare claim frequency across years, while `geom_text()` adds labels showing the exact claim frequency values above each bar.\n:::\n\n::: panel-tabset\n#### Overview\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  policy_year_metrics,\n  aes(\n    x = factor(year),\n    y = total_claims / total_exposure,\n    color = policy_type,\n    group = policy_type\n  )\n) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 5, stroke = 1) +\n  scale_color_manual(values = c(primary_color, secondary_color, third_color, fourth_color, fifth_color)) +\n  labs(title = \"Claim Frequency by Policy Type\", x = \"Year\", y = \"Claim Frequency\", color = \"Policy Type\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-28-1.png){width=1152}\n:::\n:::\n\n\n#### Third-Party + Additional Coverages\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\nfilter(policy_year_metrics, policy_type==\"CC\"),\naes(\nx=factor(year),\ny=total_claims/total_exposure,\nfill=factor(year)\n)\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_claims / total_exposure, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Claim Frequency: Third-Party + Additional Coverages\", x = \"Year\", y = \"Claim Frequency\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=1152}\n:::\n:::\n\n\n#### Comprehensive with Excess - COMP_E\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\nfilter(policy_year_metrics, policy_type==\"COMP_E\"),\naes(\nx=factor(year),\ny=total_claims/total_exposure,\nfill=factor(year)\n)\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_claims / total_exposure, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Claim Frequency: Comprehensive with Excess\", x = \"Year\", y = \"Claim Frequency\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=1152}\n:::\n:::\n\n\n#### Comprehensive without Excess - COMP_N\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\nfilter(policy_year_metrics, policy_type==\"COMP_N\"),\naes(\nx=factor(year),\ny=total_claims/total_exposure,\nfill=factor(year)\n)\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_claims / total_exposure, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Claim Frequency: Comprehensive without Excess\", x = \"Year\", y = \"Claim Frequency\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=1152}\n:::\n:::\n\n\n#### Basic Third-Party Liability - TP\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\nfilter(policy_year_metrics, policy_type==\"TP\"),\naes(\nx=factor(year),\ny=total_claims/total_exposure,\nfill=factor(year)\n)\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_claims / total_exposure, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Claim Frequency: Basic Third-Party Liability\", x = \"Year\", y = \"Claim Frequency\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-32-1.png){width=1152}\n:::\n:::\n\n\n#### Third-Party Liability + Glass - TPG\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\nfilter(policy_year_metrics, policy_type==\"TPG\"),\naes(\nx=factor(year),\ny=total_claims/total_exposure,\nfill=factor(year)\n)\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_claims / total_exposure, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Claim Frequency: Third-Party Liability + Glass\", x = \"Year\", y = \"Claim Frequency\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-33-1.png){width=1152}\n:::\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- COMP_N (Comprehensive without excess) consistently records the highest claim frequency across all policy types, increasing from approximately 0.83 (2022) to 1.17 (2024). This indicates that policyholders under this product generate claims at a substantially higher rate than other segments, suggesting COMP_N represents the highest-risk policy category within the portfolio.\n\n- The upward trend in COMP_N claim frequency over time suggests worsening claims experience or increasing portfolio risk, warranting closer monitoring in subsequent profitability analyses.\n\n- COMP_E (Comprehensive with excess) exhibits moderate but relatively stable claim frequency (\\~0.39–0.41) across years. Compared to COMP_N, the presence of an excess requirement may contribute to lower claim occurrence.\n\n- CC (Third-Party + Additional Coverages) and TPG (Third-Party + Glass) maintain lower and relatively stable claim frequencies (\\~0.20–0.25), indicating more predictable claims behaviour over time.\n\n- TP (Basic Third-Party Liability) records the lowest claim frequency overall, despite a slight increase observed in 2024.\n\n- The substantial differences in claim frequency across products indicate that policy type is strongly associated with heterogeneous risk profiles, suggesting risk exposure is not evenly distributed across insurance offerings.\n:::\n\n::: biz-box\n**Business Implication**\n\n- The persistently high and increasing claim frequency observed in COMP_N suggests this product may require premium repricing, stricter underwriting criteria, or refined risk segmentation strategies to manage deteriorating claims performance.\n\n- Products with relatively stable claim frequency may contribute to greater predictability in portfolio performance and underwriting outcomes.\n\n- Since high claim frequency does not necessarily imply poor profitability, subsequent analysis of loss ratios is required to determine whether elevated claims are sufficiently offset by premium levels.\n:::\n\n### 5.2 Loss Ratio by Policy Type Over Time\n\nLoss ratio evaluates underwriting profitability by measuring the proportion of collected premiums consumed by incurred claims. It is widely used to assess the financial performance of insurance products over time.\n\nThe metric is computed as:\n\nLoss Ratio=Total IncurredTotal PremiumLoss Ratio=\\frac{Total\\ Incurred}{Total\\ Premium}Loss Ratio=Total PremiumTotal Incurred​\n\nA line chart was selected because it effectively illustrates temporal trends and facilitates comparison of profitability across policy categories.\n\nThe visualisation compares:\n\n- `year` → x-axis (2022–2024)\n\n- `total_incurred / total_premium` → y-axis (loss ratio)\n\n- `policy_type` → colour grouping\n\nA loss ratio below 1 indicates collected premiums exceed incurred claims, suggesting underwriting profitability. Conversely, values above 1 imply claims costs exceed premium income and may indicate unprofitable products.\n\n::: panel-tabset\n#### Overview\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  policy_year_metrics,\n  aes(\n    x=factor(year),\n    y=total_incurred/total_premium,\n    color=policy_type,\n    group=policy_type\n  )\n)+\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 5, stroke = 1) +\n  scale_color_manual(values = c(primary_color, secondary_color, third_color, fourth_color, fifth_color)) +\n  labs(title = \"Loss Ratio by Policy Type\", x = \"Year\", y = \"Loss Ratio\", color = \"Policy Type\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-34-1.png){width=1152}\n:::\n:::\n\n\n#### Third-Party + Additional Coverages - CC\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  filter(\n    policy_year_metrics,\n    policy_type==\"CC\"\n  ),\n  aes(x = factor(year), \n      y = total_incurred / total_premium, \n      fill = factor(year))\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_incurred / total_premium, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Loss Ratio: Third-Party + Additional Coverages\", x = \"Year\", y = \"Loss Ratio\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-35-1.png){width=1152}\n:::\n:::\n\n\n#### Comprehensive with Excess - COMP_E\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  filter(\n    policy_year_metrics,\n    policy_type==\"COMP_E\"\n  ),\n  aes(x = factor(year), \n      y = total_incurred / total_premium, \n      fill = factor(year))\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_incurred / total_premium, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Loss Ratio: Comprehensive with Excess\", x = \"Year\", y = \"Loss Ratio\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=1152}\n:::\n:::\n\n\n#### Comprehensive without Excess - COMP_N\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  filter(\n    policy_year_metrics,\n    policy_type==\"COMP_N\"\n  ),\n  aes(x = factor(year), \n      y = total_incurred / total_premium, \n      fill = factor(year))\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_incurred / total_premium, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Loss Ratio: Comprehensive without Excess\", x = \"Year\", y = \"Loss Ratio\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=1152}\n:::\n:::\n\n\n#### Basic Third-Party Liability - TP\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  filter(\n    policy_year_metrics,\n    policy_type==\"TP\"\n  ),\n  aes(x = factor(year), \n      y = total_incurred / total_premium, \n      fill = factor(year))\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_incurred / total_premium, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Loss Ratio: Basic Third-Party Liability\", x = \"Year\", y = \"Loss Ratio\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=1152}\n:::\n:::\n\n\n#### Third-Party Liability + Glass - TPG\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(\n  filter(\n    policy_year_metrics,\n    policy_type==\"TPG\"\n  ),\n  aes(x = factor(year), \n      y = total_incurred / total_premium, \n      fill = factor(year))\n)+\n  geom_col(color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(total_incurred / total_premium, 2)), vjust = -.3, size = 10, color = text_dark, family = \"DM Sans\") +\n  scale_fill_manual(values = c(primary_color, secondary_color, third_color)) +\n  labs(title = \"Loss Ratio: Third-Party Liability + Glass\", x = \"Year\", y = \"Loss Ratio\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=1152}\n:::\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- COMP_N (Comprehensive without excess) records the highest loss ratio across all policy types, increasing from approximately 0.73 (2022) to above 1.0 (2024). By 2024, incurred claims exceed collected premiums, indicating potential underwriting losses and suggesting COMP_N represents the highest-risk and least profitable product segment within the portfolio.\n\n- The worsening loss ratio observed in COMP_N aligns with previous findings showing the highest claim frequency, reinforcing evidence of deteriorating portfolio performance within this product category.\n\n- COMP_E (Comprehensive with excess) exhibits moderately high but increasing loss ratios (0.66 → 0.79). Although remaining below 1, the upward trend suggests declining underwriting profitability over time.\n\n- TPG (Third-Party + Glass) also demonstrates a gradual increase in loss ratio (0.59 → 0.75), indicating claims costs consume an increasing proportion of premium income.\n\n- TP (Basic Third-Party Liability) shows one of the strongest relative increases in loss ratio (0.30 → 0.64) despite maintaining comparatively low claim frequency in earlier analyses. This may suggest claims become more severe rather than more frequent.\n\n- CC (Third-Party + Additional Coverages) remains relatively stable (0.59–0.66), indicating more consistent profitability across years.\n:::\n\n::: biz-box\n**Business Implication:**\n\n- The simultaneous increase in both claim frequency and loss ratio suggests COMP_N may require closer monitoring, revised pricing strategies, stricter underwriting criteria, or refined risk segmentation approaches.\n\n- The increasing loss ratio observed in TP indicates that low claim occurrence does not necessarily imply low financial risk, highlighting the importance of evaluating both claim frequency and claim severity.\n\n- Products with relatively stable loss ratios, such as CC, may contribute greater predictability to portfolio profitability.\n\n- The observed differences demonstrate that insurance products exhibit heterogeneous risk characteristics and therefore may require differentiated pricing and portfolio management strategies.\n:::\n\n### 5.3 Claim Frequency and Loss Ratio by Policy Activity Status\n\nThis analysis compares claim frequency and loss ratio between active and non-active policies across 2022–2024. The data was transformed into long format using `pivot_longer()` to enable simultaneous comparison of both performance metrics within a single visualisation.\n\nGrouped bar charts were selected because they facilitate direct comparison between claim occurrence and underwriting profitability within each year and policy status category.\n\n::: code-tip\n**Coding Details**\n\n- `pivot_longer()` reshapes claim frequency and loss ratio into a single metric column, making it easier to compare multiple performance indicators within one chart. `recode()` renames metric labels into more readable terms for presentation.\n\n- `position_dodge()` places bars and labels side-by-side instead of stacking them, allowing direct comparison between claim frequency and loss ratio across years.\n:::\n\n::: panel-tabset\n#### Active\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nstatus_metrics_long <- status_year_metrics %>%\n  mutate(claim_frequency = total_claims / total_exposure, loss_ratio = total_incurred / total_premium) %>%\n  select(year, status_group, claim_frequency, loss_ratio) %>%\n  pivot_longer(cols = c(claim_frequency, loss_ratio), names_to = \"metric\", values_to = \"value\") %>%\n  mutate(metric = recode(metric, \"claim_frequency\" = \"Claim Frequency\", \"loss_ratio\" = \"Loss Ratio\"))\n\nggplot(filter(status_metrics_long, status_group == \"Active\"), aes(x = factor(year), y = value, fill = metric)) +\n  geom_col(position = position_dodge(width = .75), width = .65, color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(value, 2)), position = position_dodge(width = .75), vjust = -.3, size = 7, color = text_dark) +\n  scale_fill_manual(values = c(\"Claim Frequency\" = primary_color, \"Loss Ratio\" = secondary_color)) +\n  labs(title = \"Claim Frequency and Loss Ratio for Active Policies\", x = \"Year\", y = \"Metric Value\", fill = \"Metric\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=1152}\n:::\n:::\n\n\n#### Not Active\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nggplot(filter(status_metrics_long, status_group == \"Not Active\"), aes(x = factor(year), y = value, fill = metric)) +\n  geom_col(position = position_dodge(width = .75), width = .65, color = \"white\", alpha = .9) +\n  geom_text(aes(label = round(value, 2)), position = position_dodge(width = .75), vjust = -.3, size = 7, color = text_dark) +\n  scale_fill_manual(values = c(\"Claim Frequency\" = primary_color, \"Loss Ratio\" = secondary_color)) +\n  labs(title = \"Claim Frequency and Loss Ratio for Not Active Policies\", x = \"Year\", y = \"Metric Value\", fill = \"Metric\") +\n  theme_va()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-41-1.png){width=1152}\n:::\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- For active policies, claim frequency remains highly stable at approximately 0.29 across all years, suggesting relatively consistent claim occurrence among retained policyholders.\n\n- The loss ratio for active policies increases gradually from 0.60 (2022) to 0.69 (2024). Although remaining below 1, the upward trend indicates weakening underwriting profitability over time.\n\n- Not active policies exhibit substantially higher claim frequency (\\~0.49–0.51) compared to active policies, indicating claims occur more frequently within this segment.\n\n- The loss ratio for not active policies consistently exceeds 1.0, ranging between 1.23 and 1.37, suggesting incurred claims exceed collected premiums and indicating persistent underwriting losses.\n\n- The simultaneous presence of higher claim frequency and loss ratio among not active policies suggests this segment represents a higher-risk and less profitable group compared to active policies.\n:::\n\n::: biz-box\n**Business Implication:**\n\n- The persistently elevated claim frequency and loss ratio observed among not active policies suggest these policies contribute disproportionately to portfolio risk and underwriting losses.\n\n- The findings may indicate that poorer claims experience is associated with increased policy cancellation or non-renewal behaviour, although further analysis is required to establish this relationship.\n\n- Investigating whether non-active policies share common characteristics, such as policy type, driver age, or vehicle profile, may support improved retention strategies and risk segmentation.\n\n- While active policies remain comparatively stable, the gradual increase in loss ratio suggests profitability should continue to be monitored over time.\n:::\n\n### 5.4 Claims vs Incurred\n\nA scatter plot with jitter was used to examine the relationship between total claims and total incurred amounts at the policy level.\n\nThe visualisation maps:\n\n- `total_claims` → x-axis (number of claims)\n\n- `total_incurred` → y-axis (total incurred claim cost)\n\nJittering (`geom_jitter()`) was applied to reduce overplotting because insurance data often contains repeated claim counts concentrated around similar values. A smoothed trend line (`geom_smooth()`) was included to highlight the overall relationship between claim occurrence and incurred cost.\n\nAdditionally, logarithmic transformations were applied to both axes (`scale_x_log10()` and `scale_y_log10()`) because claim costs are highly right-skewed. Without transformation, extreme claim values would dominate the visualisation and obscure patterns among lower-cost observations.\n\n::: code-tip\n**Coding Details**\n\n- `geom_jitter()` adds random variation to point positions to reduce overlap, making dense observations easier to visualise. `geom_smooth()` overlays a trend line to show the overall relationship between total claims and incurred amounts.\n\n- `scale_x_log10()` and `scale_y_log10()` apply logarithmic scaling to both axes, improving visibility when values are highly skewed or span a wide range.\n:::\n\n::: panel-tabset\n#### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-42-1.png){width=1152}\n:::\n:::\n\n\n#### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\nmotor_clean,\naes(\nx = total_claims + 1,\ny = total_incurred + 1\n)\n)+\ngeom_jitter(\ncolor = primary_color,\nalpha = .15\n)+\ngeom_smooth(\ncolor = secondary_color,\nse = FALSE\n)+\nscale_x_log10()+\nscale_y_log10()+\nlabs(\ntitle = \"Claims vs Incurred (Log Scale)\",\nx = \"Total Claims (log scale)\", \ny = \"Total Incurred (log scale)\"\n)+\ntheme_va()\n```\n:::\n\n:::\n\n::: obsv-box\n**Observation**\n\n- The smoothed trend line indicates a positive relationship between claim count and incurred cost, suggesting policies with more claims generally generate higher losses.\n\n- The relationship is not strictly linear, as considerable variation in incurred amounts exists among policies with similar numbers of claims, particularly between 2 and 5 claims.\n\n- The substantial vertical dispersion suggests that claim severity differs considerably even when claim frequency is similar, indicating claim count alone does not fully explain incurred losses.\n\n- Several policies with relatively few claims exhibit exceptionally high incurred amounts, implying that infrequent but severe claims may contribute disproportionately to portfolio losses.\n\n- Multiple extreme outliers exceeding 100,000 monetary units are observed despite moderate claim counts, suggesting the presence of high-severity or catastrophic claim events.\n\n- The smoothed trend appears to flatten around 4–6 claims before increasing again, indicating increases in claim count do not always correspond proportionally to increases in incurred costs.\n:::\n\n::: biz-box\n**Business Implication:**\n\n- The findings suggest that claim frequency alone is insufficient for evaluating portfolio risk, as claim severity introduces substantial variability in financial outcomes.\n\n- Policies associated with low-frequency but high-severity claims may generate significant underwriting risk despite relatively few claim events.\n\n- The presence of extreme incurred outliers suggests insurers may require targeted monitoring of high-severity segments, stronger underwriting controls, or reinsurance strategies to manage portfolio volatility.\n\n- Effective portfolio management should therefore consider both claim occurrence (frequency) and financial impact (severity) when assessing profitability and risk exposure.\n:::\n\n### 5.5 Relationship Between Driver Age, Claim Frequency, and Loss Ratio\n\nThis animated visualisation examines how driver age distributions relate to claim frequency and loss ratio across selected policy types over time (2022–2024).\n\nThe analysis focuses on CC (Third-Party + Additional Coverages) and COMP_N (Comprehensive without Excess) to compare age-based risk patterns between a relatively stable product and a higher-risk segment identified in earlier analyses.\n\nThe visual combines:\n\n- Density curves (cloud) → distribution of policyholders by age\n\n- Rain/stem plots → mean risk metric (claim frequency or loss ratio) at each age\n\n- Animation (`transition_states()`) → temporal changes across years\n\n- Faceting → comparison across policy types and risk metrics\n\nThis layered approach allows simultaneous examination of demographic concentration, risk behaviour, and temporal evolution, which would be difficult to observe using static charts alone.\n\n**Extension:**\n\nThe framework can be extended to other policy types (e.g., `COMP_E`, `TP`, `TPG`) by modifying the selected `policy_type` filter. This supports comparison of age-related risk patterns across different insurance products and enables broader portfolio segmentation analysis.\n\nThe animation cycles through yearly observations (2022–2024), allowing changes in age-related risk patterns to be observed over time.\n\n::: code-tip\n**Coding Details**\n\n- `is.finite()` keeps only valid claim frequency and loss ratio values, removing infinite results that may occur from division issues. `NA_real_` ensures missing numeric values are stored consistently as numeric `NA`.\n\n- `geom_density()` creates the driver age density “cloud”, while `after_stat()` rescales the density values so they fit visually within the plot. `geom_segment()` and `geom_point()` create the “rain” effect by showing scaled risk values below the age distribution.\n\n- `facet_grid(metric ~ policy_type)` separates the visualisation by metric and policy type, while `transition_states()` animates the chart across years.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nrisk_profile <- motor_clean %>%\n  mutate(\n    claim_frequency = if_else(\n      total_exposure > 0,\n      total_claims / total_exposure,\n      NA_real_\n    ),\n    loss_ratio = if_else(\n      total_premium > 0,\n      total_incurred / total_premium,\n      NA_real_\n    )\n  ) %>%\n  filter(\n    policy_type %in% c(\"CC\", \"COMP_N\"),\n    !is.na(year),\n    !is.na(driver_age),\n    is.finite(claim_frequency),\n    is.finite(loss_ratio)\n  ) %>%\n  mutate(\n    policy_type = recode(\n      policy_type,\n      \"CC\" = \"Third-Party + Additional Coverages\",\n      \"COMP_N\" = \"Comprehensive without Excess\"\n    )\n  )\n\nrisk_metric <- risk_profile %>%\n  group_by(year, policy_type, driver_age) %>%\n  summarise(\n    loss_ratio = mean(loss_ratio, na.rm = TRUE),\n    claim_frequency = mean(claim_frequency, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  pivot_longer(\n    cols = c(loss_ratio, claim_frequency),\n    names_to = \"metric\",\n    values_to = \"value\"\n  ) %>%\n  group_by(year, policy_type, metric) %>%\n  mutate(\n    value_scaled = value / max(value, na.rm = TRUE) * 1.2\n  ) %>%\n  ungroup() %>%\n  mutate(\n    metric = recode(\n      metric,\n      \"loss_ratio\" = \"Loss Ratio\",\n      \"claim_frequency\" = \"Claim Frequency\"\n    )\n  )\n\nggplot() +\n  geom_density(\n    data = risk_profile,\n    aes(\n      x = driver_age,\n      y = after_stat(density / max(density) * .8)\n    ),\n    fill = secondary_color,\n    color = secondary_color,\n    alpha = .65,\n    adjust = 2\n  ) +\n  geom_segment(\n    data = risk_metric,\n    aes(\n      x = driver_age,\n      xend = driver_age,\n      y = 0,\n      yend = -value_scaled,\n      color = metric\n    ),\n    alpha = .45,\n    linewidth = .8\n  ) +\n  geom_point(\n    data = risk_metric,\n    aes(\n      x = driver_age,\n      y = -value_scaled,\n      color = metric\n    ),\n    size = 2.2,\n    alpha = .8\n  ) +\n  scale_color_manual(\n    values = c(\n      \"Claim Frequency\" = primary_color,\n      \"Loss Ratio\" = fourth_color\n    )\n  ) +\n  facet_grid(\n    metric ~ policy_type\n  ) +\n  scale_y_continuous(\n    limits = c(-1.35, .9),\n    breaks = c(-1.2, 0, .8),\n    labels = c(\"Higher Risk\", \"0\", \"Age Density\")\n  ) +\n  labs(\n    title = \"Age-Based Risk Profiles Across Selected Policy Types | Year: {closest_state}\",\n    subtitle = \"Cloud = Driver age density | Rain = Mean risk metric by age\",\n    x = \"Driver Age\",\n    y = NULL,\n    color = \"Metric\"\n  ) +\n  transition_states(\n    year,\n    transition_length = 2,\n    state_length = 5\n  ) +\n  theme_va() +\n  theme(\n    legend.position = \"none\",\n    panel.grid.major.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-44-1.gif)\n:::\n:::\n\n\n::: obsv-box\n**Observation**\n\n- Across all years, policyholders are primarily concentrated between approximately 35–65 years, indicating that middle-aged drivers dominate both selected policy categories.\n\n- COMP_N (Comprehensive without excess) consistently exhibits higher claim frequency and loss ratio across multiple age groups compared to CC, reinforcing earlier findings that COMP_N represents the highest-risk product segment.\n\n- Elevated risk metrics in COMP_N persist despite similar age concentration patterns, suggesting that policy characteristics may influence risk beyond demographic composition alone.\n\n- Risk metrics vary across ages, indicating that driver age does not have a uniform relationship with claim behaviour or profitability.\n\n- The animation suggests that risk profiles evolve over time, particularly within COMP_N, where higher claim frequency and loss ratios become more pronounced across later years.\n\n- The coexistence of dense middle-aged populations and elevated risk metrics implies that high-volume demographic groups may contribute disproportionately to portfolio performance outcomes.\n:::\n\n::: biz-box\n**Business Implication**\n\n- The persistence of elevated risk metrics across age groups within COMP_N suggests that product design or underwriting conditions may influence portfolio risk beyond age effects alone.\n\n- Age-based segmentation may improve pricing precision, but demographic characteristics should be evaluated together with policy type to avoid oversimplified risk assessment.\n\n- Since middle-aged drivers represent the largest proportion of policyholders, changes in claims behaviour within this demographic may have substantial implications for overall portfolio profitability.\n\n- Animated temporal analysis highlights how risk patterns evolve over time, supporting proactive monitoring of emerging high-risk segments.\n:::\n\n## 6 Summary and Future Research\n\nOur analysis of the motor insurance portfolio examined relationships between policy types, demographics, retention behaviour, claim frequency, incurred losses, and underwriting profitability. Overall, the findings revealed substantial heterogeneity in risk and profitability across products and customer segments, suggesting portfolio performance is associated with multiple interacting factors rather than a single characteristic.\n\n### 6.1 Key Findings:\n\n- The portfolio is highly concentrated in Third-Party + Additional Coverages (CC), indicating that overall portfolio performance may be disproportionately influenced by a small number of dominant products.\n\n- Policyholders are primarily concentrated within middle-aged groups (approximately 35–60 years), suggesting this demographic contributes substantially to portfolio exposure.\n\n- The proportion of inactive policies increases over time, potentially indicating weakening customer retention and increasing churn risk.\n\n- COMP_N (Comprehensive without excess) consistently demonstrates the highest claim frequency and loss ratio, exceeding a loss ratio of 1.0 in 2024. This suggests the segment may have transitioned into an underwriting loss position, making it the highest-risk and least profitable product within the portfolio.\n\n- In contrast, CC (Third-Party + Additional Coverages) maintains comparatively stable claim frequency and loss ratios, indicating more predictable underwriting performance.\n\n- Policies with relatively few claims may still generate substantial incurred costs, suggesting claim severity is an important determinant of portfolio volatility alongside claim frequency.\n\n- Not active policies exhibit both higher claim frequency and higher loss ratios compared to active policies, indicating these segments may contribute disproportionately to portfolio risk and underwriting losses.\n\n- Age-based analyses suggest that risk behaviour evolves over time and differs across policy types, highlighting potential interactions between demographic characteristics and product-specific risk exposure.\n\nCollectively, the findings suggest that policy type, retention behaviour, claim frequency, and claim severity are associated with differences in portfolio risk, profitability, and volatility. Products exhibiting persistently elevated claim frequency and loss ratios appear more vulnerable to deteriorating underwriting performance, while severe but infrequent claims may contribute disproportionately to portfolio volatility.\n\nHowever, as the current analysis is exploratory in nature, these relationships should be interpreted as associations rather than confirmed causal influences. Additional statistical testing is required to determine whether observed patterns represent significant drivers of profitability and risk.\n\n### 6.2 Recommendations for Future Research\n\n#### Confirmatory and Statistical Analysis\n\nThe current study identifies patterns and associations between portfolio characteristics and insurance performance but does not establish causal relationships. Future research should incorporate statistical hypothesis testing and confirmatory analysis to determine whether variables such as policy type, retention status, claim frequency, age, and claim severity significantly influence profitability and portfolio volatility.\n\nPotential approaches include:\n\n- ANOVA / t-tests → compare profitability and claims metrics across policy groups\n\n- Chi-square tests → assess relationships between categorical variables\n\n- Correlation analysis → quantify strength of associations between portfolio characteristics and risk measures\n\n- Regression modelling → identify statistically significant predictors of claim frequency, loss ratio, or profitability\n\n- Survival analysis → investigate factors associated with customer retention and policy cancellation behaviour\n\nThese methods would provide stronger evidence regarding whether observed relationships represent true drivers of profitability and volatility rather than coincidental patterns.\n\n#### Customer Retention and Churn Analysis\n\nThe increasing proportion of inactive policies suggests potential deterioration in customer retention over time. Future studies should investigate whether claim frequency, loss ratios, demographics, or policy characteristics are associated with policy cancellation or non-renewal behaviour.\n\nUnderstanding these relationships may support improved customer retention strategies, pricing decisions, and long-term portfolio stability.\n\n#### Claim Severity and Extreme Loss Analysis\n\nWhile claim frequency explains how often claims occur, portfolio profitability may also be influenced by high-severity but infrequent claims. Further analysis of extreme incurred losses and outlier events could improve understanding of catastrophic risks and support decisions relating to:\n\n- pricing strategies,\n\n- underwriting controls,\n\n- reinsurance arrangements,\n\n- portfolio volatility management.\n\n#### Advanced Risk Segmentation\n\nFuture research should examine interactions between variables such as:\n\n- driver age,\n\n- policy type,\n\n- retention status,\n\n- claim frequency,\n\n- claim severity,\n\n- profitability indicators.\n\nMultivariate approaches may reveal complex risk segments not observable through pairwise comparisons and support more precise pricing and underwriting strategies.\n\n#### Longitudinal Portfolio Monitoring\n\nExtending analysis beyond the 2022–2024 period would enable evaluation of longer-term changes in:\n\n- portfolio composition,\n\n- profitability,\n\n- customer behaviour,\n\n- claims experience,\n\n- retention patterns.\n\nLongitudinal studies may reveal structural shifts in risk behaviour and improve the insurer’s ability to anticipate emerging trends.\n\n#### Incorporating Additional Risk Factors\n\nFuture analyses could incorporate variables including:\n\n- vehicle characteristics,\n\n- geographic factors,\n\n- driving behaviour,\n\n- usage patterns,\n\n- external economic conditions,\n\nwhich may influence claims experience but were not explored within the current scope. Including these variables may provide a more comprehensive understanding of portfolio risk determinants.\n\nBy extending analysis towards confirmatory testing, predictive modelling, and deeper risk segmentation, future research may provide stronger evidence regarding the factors driving insurance profitability and volatility, thereby supporting more targeted underwriting strategies and sustainable portfolio management decisions.\n\n## 7 References\nKam, T. S. (2023). Visualising Distribution. R for Visual Analytics. https://r4va.netlify.app/chap09\n\nScherer, C. (2019). A ggplot2 Tutorial for Beautiful Plotting in R. Cedric Scherer. https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/\n(Useful for plot titles, labels, themes, fonts, spacing, annotations, and overall visual styling.)",
    "supporting": [
      "Take-Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}